server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://ec2-107-22-122-106.compute-1.amazonaws.com:5432/d25gq2nbot5l4h
    username: cftrmmjqablphq
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  flyway:
    baseline-on-migrate: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
